/**
 * Reads theme colors from content/site-data.json and writes CSS custom properties
 * to app/theme-vars.css. Run before dev/build so Tailwind picks up client branding.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const siteDataPath = join(root, "content", "site-data.json");
const outputPath = join(root, "app", "theme-vars.css");

const siteData = JSON.parse(readFileSync(siteDataPath, "utf8"));
const { primaryColor, accentColor, backgroundColor } = siteData.theme;

const WCAG_AA_NORMAL = 4.5;

function hexToRgb(hex) {
  const normalized = hex.replace("#", "");
  return [
    parseInt(normalized.slice(0, 2), 16),
    parseInt(normalized.slice(2, 4), 16),
    parseInt(normalized.slice(4, 6), 16),
  ];
}

function rgbToHslString([r, g, b]) {
  const rn = r / 255;
  const gn = g / 255;
  const bn = b / 255;
  const max = Math.max(rn, gn, bn);
  const min = Math.min(rn, gn, bn);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case rn:
        h = ((gn - bn) / d + (gn < bn ? 6 : 0)) / 6;
        break;
      case gn:
        h = ((bn - rn) / d + 2) / 6;
        break;
      default:
        h = ((rn - gn) / d + 4) / 6;
        break;
    }
  }

  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

function hexToHsl(hex) {
  return rgbToHslString(hexToRgb(hex));
}

function relativeLuminance([r, g, b]) {
  const channels = [r, g, b].map((value) => {
    const normalized = value / 255;
    return normalized <= 0.03928
      ? normalized / 12.92
      : ((normalized + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2];
}

function contrastRatio(foreground, background) {
  const l1 = relativeLuminance(foreground);
  const l2 = relativeLuminance(background);
  return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
}

function hslStringToRgb(hslString) {
  const [hRaw, sRaw, lRaw] = hslString.split(" ");
  const h = parseFloat(hRaw);
  const s = parseFloat(sRaw) / 100;
  const l = parseFloat(lRaw) / 100;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  let r = 0;
  let g = 0;
  let b = 0;

  if (h < 60) [r, g, b] = [c, x, 0];
  else if (h < 120) [r, g, b] = [x, c, 0];
  else if (h < 180) [r, g, b] = [0, c, x];
  else if (h < 240) [r, g, b] = [0, x, c];
  else if (h < 300) [r, g, b] = [x, 0, c];
  else [r, g, b] = [c, 0, x];

  return [(r + m) * 255, (g + m) * 255, (b + m) * 255];
}

function blendRgb(base, overlay, alpha) {
  return base.map((value, index) => value * (1 - alpha) + overlay[index] * alpha);
}

function findAccessibleMutedForeground(backgroundRgb, primaryRgb) {
  const surfaces = [
    backgroundRgb,
    hslStringToRgb("210 20% 96%"),
    blendRgb(backgroundRgb, primaryRgb, 0.05),
    blendRgb(backgroundRgb, primaryRgb, 0.1),
  ];

  for (let lightness = 46; lightness >= 30; lightness -= 1) {
    const candidate = hslStringToRgb(`215 16% ${lightness}%`);
    if (
      surfaces.every(
        (surface) => contrastRatio(candidate, surface) >= WCAG_AA_NORMAL
      )
    ) {
      return `215 16% ${lightness}%`;
    }
  }
  return "215 16% 40%";
}

function findAccessibleAccentText(accentRgb, backgroundRgb) {
  for (let factor = 0.95; factor >= 0.5; factor -= 0.02) {
    const candidate = accentRgb.map((value) => Math.round(value * factor));
    if (contrastRatio(candidate, backgroundRgb) >= WCAG_AA_NORMAL) {
      return rgbToHslString(candidate);
    }
  }
  return rgbToHslString(accentRgb.map((value) => Math.round(value * 0.7)));
}

function findAccessibleWhatsApp() {
  const candidates = ["#128C7E", "#0f766e", "#15803D", "#166534", "#075E54"];
  const white = [255, 255, 255];
  for (const hex of candidates) {
    const rgb = hexToRgb(hex);
    if (contrastRatio(white, rgb) >= WCAG_AA_NORMAL) {
      return hex;
    }
  }
  return "#075E54";
}

const backgroundRgb = hexToRgb(backgroundColor);
const accentRgb = hexToRgb(accentColor);
const primaryRgb = hexToRgb(primaryColor);
const mutedForeground = findAccessibleMutedForeground(backgroundRgb, primaryRgb);
const accentText = findAccessibleAccentText(accentRgb, backgroundRgb);
const whatsappColor = findAccessibleWhatsApp();

const css = `/* Auto-generated by scripts/sync-theme.mjs — do not edit manually */
:root {
  --background: ${hexToHsl(backgroundColor)};
  --foreground: 222 47% 11%;
  --card: ${hexToHsl(backgroundColor)};
  --card-foreground: 222 47% 11%;
  --popover: ${hexToHsl(backgroundColor)};
  --popover-foreground: 222 47% 11%;
  --primary: ${hexToHsl(primaryColor)};
  --primary-foreground: 0 0% 100%;
  --secondary: 210 20% 96%;
  --secondary-foreground: 222 47% 11%;
  --muted: 210 20% 96%;
  --muted-foreground: ${mutedForeground};
  --accent: ${hexToHsl(accentColor)};
  --accent-foreground: 0 0% 100%;
  --accent-text: ${accentText};
  --destructive: 0 84% 49%;
  --destructive-foreground: 0 0% 100%;
  --whatsapp: ${hexToHsl(whatsappColor)};
  --whatsapp-foreground: 0 0% 100%;
  --whatsapp-icon: 142 70% 49%;
  --border: 214 20% 90%;
  --input: 214 20% 90%;
  --ring: ${hexToHsl(primaryColor)};
  --radius: 0.75rem;
}
`;

writeFileSync(outputPath, css, "utf8");
console.log("Theme synced from content/site-data.json → app/theme-vars.css");
